### ISSUE TITLE
RAMPART version 1.0

### ISSUE THREAD

**Issue by Psy-Fer** [artic-network/artic-ncov2019#16]
Hey,

RAMPART version 1.0 can't do remote browser.
Can we get the yml file updated to run version 1.1.0? 
I've got RAMPART running in it's own env from that repo, running on the protocols from this repo, and it's working really well. I just remove the RAMPART line from the setup yml file.

Cheers,

**Comment by rambaut** [comment]
I want to go through some testing and final tweaks before releasing v1.1 but we can try to accelerate this - I also need remote browser access.

**Comment by lskatz** [comment]
`references.fasta` ends with a `"`.  Is that an issue?

**Comment by jameshadfield** [comment]
@Psy-Fer closing this as 1.2.0 is the latest conda version and remote broswer support was part of the 1.1.0 release. Please reopen if this is not the case!

@lskatz -- I don't completely understand, could you make a new issue if this is still problematic? Thanks

**Comment by Psy-Fer** [comment]
Absolute legend.
All works :)
