### ISSUE TITLE
--skip-nanopolish and --dry-run

### ISSUE THREAD

**Issue by mi-koch** [artic-network/artic-ncov2019#20]
I am looking to get the pipeline up and running before we sequence data. I have downloaded some publicly available fastqs to try it out.
The medaka part works fine, however for the `artic minion`, I cannot provide the fast5 required, as I have not found a dataset.

So I tried a `--dry-run` like so: 

`artic minion --normalise 200 --threads 4 --scheme-directory ~/primer_schemes/ --read-file  ~/reads/$sample.fastq --dry-run nCoV-2019/V3 $sample`

Output: "Must specify FAST5 directory and sequencing summary for nanopolish mode."

Is it correct, that for `artic minion`, I always need a fast5? When I tried to `--skip-nanopolish`, I got the same output as above.

Are those two non-functioning flags or am I doing something wrong?
Thanks for advising!

**Comment by nickloman** [comment]
Hi there,

To run nanopolish you must have FAST5. There is some FAST5 data available from https://community.artic.network/t/links-to-raw-fast5-fastq-data-for-artic-protocol/17 if that's of use.

If you want to try the experimental Medaka version, you don't need FAST5 but must specify --medaka on the command line.

Let me know if that helps.

**Comment by mi-koch** [comment]
Thanks for the swift response!

I will try the dataset from the CADDE project, thank you.

So just to confirm, the --dry-run and --skip-nanopolish are not functional yet or did I do something wrong?

**Comment by nickloman** [comment]
--dry-run will just print out the commands

--skip-nanopolish isn't something you want to do! I might remove it.

**Comment by mi-koch** [comment]
Thanks for your answers!
Stay safe
