### ISSUE TITLE
No variant.tab output

### ISSUE THREAD

**Issue by deearahman** [artic-network/artic-ncov2019#23]
I don’t have the variant output. Was there any step that I missed?

**Comment by garfinjm** [comment]
Having the same issue here. No `samplename.variants.tab` output for any of my samples. Everything else looks OK though.

**Comment by vehuardo** [comment]
Same here!

**Comment by will-rowe** [comment]
Sorry - just come across this.

Looks like this output file got silently dropped from the output during transition from v1.0.0 -> [v1.1.0-rc](https://github.com/artic-network/fieldbioinformatics/tree/1.1.0-rc). All information is available in the VCF.

We will remove this from the SOP for now. Please raise an issue over on [the artic pipeline](https://github.com/artic-network/fieldbioinformatics) if you want this adding back in.
