### ISSUE TITLE
Adapters not removed from SP1 reads

### ISSUE THREAD

**Issue by MaestSi** [artic-network/artic-ncov2019#26]
Hi,
I tried out artic pipeline v1.0.0 on [SP1 test data](https://cadde.s3.climb.ac.uk/SP1-raw.tgz) using the following instructions, after performing basecalling:
```
artic guppyplex --min-length 400 --max-length 700 --directory basecalling/ --prefix SP1
mv SP1_.fastq SP1.fastq
artic minion --normalise 200 --threads 4 --scheme-directory primer_schemes --read-file SP1.fastq --fast5-directory SP1-fast5-raw --sequencing-summary basecalling/sequencing_summary.txt nCoV-2019/V1 SP1
```
I was not completely sure about the nCoV-2019/V1 version of the protocol, could you please confirm the specified version is correct? After the pipeline finished running successfully, I uploaded to IGV the **SP1.primertrimmed.rg.sorted.bam** file. I was expecting not to see any adapters or PCR primers, but based on the soft-clipping, it looks like those have not been removed. Is this a bug or it is due to the primers scheme specified not matching the actual one?
![SP1 primertrimmed rg sorted](https://user-images.githubusercontent.com/19406763/78679279-4dbaf580-78ea-11ea-8b2b-5dc0e8d3225d.png)
Thanks,
Simone

**Comment by nickloman** [comment]
Indeed, that doesn't look right to me.

You look to have used the right primer scheme.

The expected result is that the edges of the primers are removed through the use of soft clips.

Is IGV showing the soft clips? (E.g. Preferences: Show soft-clipped bases)

Can you try loading into Tablet and seeing what that looks like?

**Comment by nickloman** [comment]
I loaded an example dataset into IGV. It should look like this:

![image](https://user-images.githubusercontent.com/116577/78682203-99b76b80-78e5-11ea-89a8-41870e07c321.png)

If you turn on "Show soft-clipped bases" it looks like this:

![image](https://user-images.githubusercontent.com/116577/78682312-ba7fc100-78e5-11ea-9d60-5d31afa76b41.png)

This is expected.

**Comment by MaestSi** [comment]
Yes, IGV is showing the soft-clipped bases, all those coloured portions of the reads are the soft-clipped bases. After seeing your example, I think that what I got is very similar to what you have, don't you think so? I did not know that the edges of the primers were removed through soft-clipping, I was simply expecting them to be trimmed. Tablet visualization looks like this:
![Tablet](https://user-images.githubusercontent.com/19406763/78683033-0e42d800-78ef-11ea-8c82-0addea4c48ba.png)
Thanks

**Comment by nickloman** [comment]
OK, sounds like things working as expected then.

**Comment by MaestSi** [comment]
Yes, thank you for your prompt reply. So, also in case multiple samples are sequenced in a single run and demultiplexing is performed with guppy_barcoder, adapters should not (or must not?) be removed with **--trim_barcodes** parameter, is it correct? Based on the [sop](https://artic.network/ncov-2019/ncov2019-bioinformatics-sop.html) it looks like that is the case. Just one more information: based on the sop, the official artic bioinformatics protocol is the one [here](https://github.com/artic-network/artic-ncov2019), but if I go to the Nanopore website and download pcr-tiling-ncov-PTC_9096_v109_revE_06Feb2020-minion file, the suggested github repository is [this one](https://github.com/artic-network/fieldbioinformatics). Which one is the most up to date?
Thanks in advance,
Simone

**Comment by nickloman** [comment]
The pipelines are slightly different, but I cannot comment directly on the ONT version. We don't trim adapters but it would be fine if you do.

**Comment by nickloman** [comment]
Oh sorry, I misread your question. The artic-ncov2019 is the repository you want: it pulls in the fieldbioinformatics pipeline directly.

**Comment by MaestSi** [comment]
Thank you again. I think you thought I was asking about the nanopolish VS medaka pipelines.
Best wishes,
Simone
