### ISSUE TITLE
Max of 400X

### ISSUE THREAD

**Issue by charreca** [artic-network/artic-ncov2019#37]
Hi!
 We currently use ARTIC bioinformatics workflow to analyze raw nanopore SARS-CoV2 reads. We achieve a maximum of 400x coverage across regions with no overlapping amplicons for each sample. Is it normal to obtain a similar result for each sample?
Is there a limit of depth that we can change in the pipeline? 
[artic_example.pdf](https://github.com/artic-network/artic-ncov2019/files/4757205/artic_example.pdf)

Thanks for your answer, 

Caroline

**Comment by nickloman** [comment]
This comes from the --normalise parameter: a value of 200 will give you 200x in each direction.

We have determined that adding more depth does not improve the results.

**Comment by charreca** [comment]
Ok many thanks for your answer.
Just one additional question: what is the minimum of depth in your pipeline to call a consensus? For the others Illumina approaches the thereshold is usually set at 10X. With ONT approach, is it higher to overcome the higher error rate of nanopore sequencing?

Caroline

**Comment by will-rowe** [comment]
Hi @charreca. Sorry for only having seen this now.

The consensus sequence will be masked with Ns wherever a position has <20X depth of coverage. We also mask out positions where called variants have failed to pass the variant filters. Hope this helps. We have recently updated our [documentation](https://artic.readthedocs.io/en/latest/) to give more detail on the pipeline. Please open a new issue in https://github.com/artic-network/fieldbioinformatics if you have any further questions.
