### ISSUE TITLE
artic_plot_amplicon_depth crash in batch 

### ISSUE THREAD

**Issue by Mattstorey** [artic-network/artic-ncov2019#39]
I'm loving the amplicon coverage plots, great for debugging sequencing and assemblies.   

However, I get this error when I run the pipeline in a non-interactive shell:

```qt.qpa.xcb: could not connect to display localhost:18.0
qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.
```

Some issues with port forwarding? 
Can I block the call to ```artic_plot_amplicon_depth```

**Comment by will-rowe** [comment]
Thanks for raising this. I'll look into it - it would be good if we can keep the plotting functionality (you can't currently block the call via the CLI).

Are you using conda to install?
