### ISSUE TITLE
Error when running the MinION pipeline command.

### ISSUE THREAD

**Issue by GeorgiM26** [artic-network/artic-ncov2019#42]
Hello,
Whenever i am running the minION pipeline command I run into an error which I am unable to decipher and, hence, troubleshoot. 
In the following, please find the exact error I am getting:

Command Used:

> artic minion --normalise 200 --scheme-directory ~/artic-ncov2019/primer_schemes/ --read-file Aug24_sample1.fastq --fast5-directory ../../../fast5_skip/ --sequencing-summary ../../../Basecalling_skipped/sequencing_summary.txt ~/artic-ncov2019/primer_schemes/nCoV-2019/V3/ Sample1

Error message:

> Traceback (most recent call last):
>   File "/home/bio/miniconda3/envs/artic-ncov2019/bin/artic", line 10, in <module>
>     sys.exit(main())
>   File "/home/bio/miniconda3/envs/artic-ncov2019/lib/python3.6/site-packages/artic/pipeline.py", line 216, in main
>     args.func(parser, args)
>   File "/home/bio/miniconda3/envs/artic-ncov2019/lib/python3.6/site-packages/artic/pipeline.py", line 35, in run_subtool
>     submodule.run(parser, args)
>   File "/home/bio/miniconda3/envs/artic-ncov2019/lib/python3.6/site-packages/artic/minion.py", line 23, in run
>     scheme_name, scheme_version = args.scheme.split('/')
> ValueError: too many values to unpack (expected 2)

N.B: Please note that the artic environment was getting stuck at solving environment with the 64-bit python 3.6 version of miniconda. Therefore it was installed via the latest version of miniconda3 (with Py3.8). I am unsure if this is contributing to the error. Also, please do excuse the hectic directory arrangement in the command. 

Thank you very much.
Sincerely, Georgi Merhi.

**Comment by nickloman** [comment]
The last part of the command should read:

```nCoV-2019/V3 Sample1```

rather than:

```~/artic-ncov2019/primer_schemes/nCoV-2019/V3/ Sample1```

**Comment by GeorgiM26** [comment]
Thank you Professor Loman, everything ran perfectly!
