### ISSUE TITLE
Create environment with Conda

### ISSUE THREAD

**Issue by Peppie-Moony** [artic-network/artic-ncov2019#51]
Hi I tried to install the artic-ncov2019 workflow as was stated on the website (https://artic.network/ncov-2019/ncov2019-bioinformatics-sop.html)
but when I tried the command
conda env create -f environment.yml

I always get the following:
<pre>Collecting package metadata (repodata.json): failed

CondaHTTPError: HTTP 500 INTERNAL SERVER ERROR for url &lt;https://conda.anaconda.org/artic-network/linux-64/repodata.json&gt;
Elapsed: 00:14.503821
CF-RAY: 61721b244fd6dfdb-FRA

A remote server error occurred when trying to retrieve this URL.

A 500-type error (e.g. 500, 501, 502, 503, etc.) indicates the server failed to
fulfill a valid request.  The problem may be spurious, and will resolve itself if you
try your request again.  If the problem persists, consider notifying the maintainer
of the remote server.

What is wrong? If I update conda with (conda update conda) this is possible without a problem. So it seems the server problem occurs only with the artic environment.yml

**Comment by will-rowe** [comment]
Hi @Peppie-Moony 

Thanks for getting in touch and I'm sorry you're having trouble. I'm not an expert with conda so am not sure why this isn't working but I can try and help.

Can you install other packages via conda? And can you create environments from other env.yml files?

In a new conda environment, can you try this and let me know if it works:

```
conda install -c bioconda -c conda-forge artic
```

**Comment by Peppie-Moony** [comment]
Thanks, for the reply. It worked just when I tried it some days later. Seems that the server/internet site just was not available on the day I first tried it.

**Comment by maansisrivastava** [comment]
> Thanks, for the reply. It worked just when I tried it some days later. Seems that the server/internet site just was not available on the day I first tried it.

@Peppie-Moony Since you have worked on it before, can you please help me? I am unable to create env from  environment.yml
