### ISSUE TITLE
which version to use

### ISSUE THREAD

**Issue by Shaokang123** [artic-network/artic-ncov2019#52]
May I ask the difference of this pipeline and https://github.com/artic-network/fieldbioinformatics? It seems the later one updated more frequently, but this version is the one used in ARTIC network SOP https://artic.network/ncov-2019/ncov2019-bioinformatics-sop.html 

Any suggestions? Thanks.

**Comment by will-rowe** [comment]
Hi @Shaokang123 

That's a good question! In terms of differences between this repo and the one at [fieldbioinformatics repo](https://github.com/artic-network/fieldbioinformatics), the ARTIC pipeline itself is developed at the [fieldbioinformatics repo](https://github.com/artic-network/fieldbioinformatics) - this is where the code lives and where you can download the development version or one of the releases.

This repository (artic-ncov2019) is more of a timestamped collection of resources for performing the [ARTIC Network SOP](https://artic.network/ncov-2019/ncov2019-bioinformatics-sop.html). It is essentially just a conda environment which contains the ARTIC pipeline, as well as a few other resources (such as RAMPART).
 
The version of the ARTIC pipeline in the SOP will be periodically updated when we are happy with the latest pipeline changes. So in a few days/weeks we will update this repository to use the latest release of the ARTIC pipeline found at [fieldbioinformatics repo](https://github.com/artic-network/fieldbioinformatics).

As a side note -  if you just want the latest ARTIC pipeline, you can now install direct from conda:
```
conda create -n artic-env
conda activate artic-env
conda install -c bioconda -c conda-forge artic
```

**Comment by Shaokang123** [comment]
@will-rowe great, thanks for your reply. Appreciate your help.

**Comment by Shaokang123** [comment]
Hi @will-rowe, if possible, may I ask for when will the SOP version of artic be updated?

**Comment by will-rowe** [comment]
Hopefully soon - just waiting on a code review from Nick before we make the next release and then update all the envs/SOPs across artic. Sorry I can't be more exact.

**Comment by Shaokang123** [comment]
@will-rowe great, thanks so much, look forward to trying the new version
