### ISSUE TITLE
ambiguity sequences in assembly

### ISSUE THREAD

**Issue by Shaokang123** [artic-network/artic-ncov2019#55]
I know artic can generate "N" as ambiguity sequences. But will artic pipeline generate other IUPAC ambiguity codes in assembly? I guess the answer is no, right? Thanks for any help.

**Comment by will-rowe** [comment]
Hi @Shaokang123 

Yes - the pipeline only introduces N into the consensus (at low coverage and low quality variant regions), it does not introduce any other IUPAC codes.
