### ISSUE TITLE
Invalid BED file column 5

### ISSUE THREAD

**Issue by nathanhaigh** [artic-network/artic-ncov2019#66]
Column 5 of the following BED files are not valid: `nCoV-2019.scheme.bed` and `nCoV-2019.bed`. Column 5 is supposed to be an integer score in the interval [0,1000]. As such, doing things like converting the file to BigBed format (using `bedToBigBed`) for visualisation in genome browsers fails for such files.

**Comment by will-rowe** [comment]
Hi @nathanhaigh 

Yes, these don't conform to the BED standard. The `*.scheme.bed` files were actually replaced by `*.primer.bed` files in a later release of primal scheme, and these conform to BED standard (even though we hijack the 6th column for strand).

So try using the more recent version of the scheme files for your application. More details on our schemes are found in the [artic primer scheme repo](https://github.com/artic-network/primer-schemes#updated-scheme-file-format)

**Comment by nathanhaigh** [comment]
Great - thanks for the explanation and heads-up with the other repo!
