### ISSUE TITLE
Using customized 'Primer' for ONT sequencing data

### ISSUE THREAD

**Issue by chantisakee** [artic-network/artic-ncov2019#68]
Hi,

I have a question about optimizing pipeline using 'customised primer'. 
According to 'Run the MinION pipeline' step, what kind of data should I have to put my customized primer in order to replace 'nCoV-2019/V3' parameter.

Thank you in advance,
Chantisa

**Comment by chantisakee** [comment]
I do actually found how to create primer scheme for our own pipeline in document.

:] thanks

**Comment by deearahman** [comment]
> I do actually found how to create primer scheme for our own pipeline in document.
> 
> :] thanks

Hi,

Do you mind sharing how this is sorted out? I am trying out V4 but not sure how to set up for the artic analysis. 

Thanks
