### ISSUE TITLE
samtools command failed (align-trim)

### ISSUE THREAD

**Issue by bernardowerner** [artic-network/artic-ncov2019#70]
Hello,

Following the nCoV-2019 novel coronavirus bioinformatics protocol, when I try to run the "Run the MinION pipeline" part

`artic minion --normalise 200 --threads 4 --scheme-directory ~/artic-ncov2019/primer_schemes --read-file run_name_barcode03.fastq --fast5-directory path_to_fast5 --sequencing-summary path_to_sequencing_summary.txt nCoV-2019/V3 samplename`

...it stops with the following error message: "samtools sort: failed to read header from "-""

What could be the trouble here? A different samtools version maybe?

Best regards,
Bernardo Werner

**Comment by lt116** [comment]
Hi Bernardo
Sorry to reopen a closed thread, but I was wondering if you managed to find a solution to this (or even if this was the issue)? I am getting the exact same error (running artic through nextflow) and this is literally the only thing to be found online regarding it.
